LINEAGE_OPEN = "<!-- LINEAGE_SUMMARY -->"
LINEAGE_CLOSE = "<!-- /LINEAGE_SUMMARY -->"
TRANSFORMATION_OPEN = "<!-- TRANSFORMATION_SUMMARY -->"
TRANSFORMATION_CLOSE = "<!-- /TRANSFORMATION_SUMMARY -->"
